WITH TBL AS (
  SELECT PRODUCTS.PRODUCTLINE,
       FORMAT_DATE("%Y-%m", ORDERS.ORDERDATE) AS YEARMONTH,
       ROUND(SUM(DETAILS.QUANTITYORDERED * DETAILS.PRICEEACH), 2) AS SALES
  FROM `classic_motors.products` AS PRODUCTS
  INNER JOIN `classic_motors.orderdetails` AS DETAILS
  ON PRODUCTS.PRODUCTCODE = DETAILS.PRODUCTCODE
  INNER JOIN `classic_motors.orders` AS ORDERS
  ON DETAILS.ORDERNUMBER = ORDERS.ORDERNUMBER
  GROUP BY PRODUCTS.PRODUCTLINE, YEARMONTH
)

SELECT *,
       ROUND(SALES / LAG(SALES) OVER (PARTITION BY PRODUCTLINE ORDER BY YEARMONTH) - 1, 4) AS PERCENTCHANGE
FROM TBL
ORDER BY PERCENTCHANGE DESC