SELECT FORMAT_DATE("%B", ORDERS.ORDERDATE) AS MONTH,
       ROUND(SUM((DETAILS.PRICEEACH - PRODUCTS.BUYPRICE) * DETAILS.QUANTITYORDERED), 2) AS PROFIT
FROM `classic_motors.orders` AS ORDERS
INNER JOIN `classic_motors.orderdetails` AS DETAILS
ON ORDERS.ORDERNUMBER = DETAILS.ORDERNUMBER
INNER JOIN `classic_motors.products` AS PRODUCTS
ON DETAILS.PRODUCTCODE = PRODUCTS.PRODUCTCODE
WHERE FORMAT_DATE("%Y", ORDERS.ORDERDATE) = "2021"
GROUP BY MONTH
ORDER BY PROFIT DESC