WITH
TBL AS (
  SELECT CUSTOMERS.CUSTOMERNAME AS NAME,
         DATE_DIFF(MAX(ORDERS.ORDERDATE), MIN(ORDERS.ORDERDATE), MONTH) AS MONTHS,
         ROUND(SAFE_DIVIDE(SUM(DETAILS.QUANTITYORDERED * DETAILS.PRICEEACH), DATE_DIFF(MAX(ORDERS.ORDERDATE), MIN(ORDERS.ORDERDATE), MONTH)), 2) AS AVG_PER_MONTH,
         COUNT(*) AS ORDERS,
         ROUND(AVG(DETAILS.QUANTITYORDERED * DETAILS.PRICEEACH), 2) AS AVG_PER_ORDER,
         ROUND(SUM(DETAILS.QUANTITYORDERED * DETAILS.PRICEEACH), 2) AS TOTAL,
  FROM `classic_motors.customers` AS CUSTOMERS
  INNER JOIN `classic_motors.orders` AS ORDERS
  ON CUSTOMERS.CUSTOMERNUMBER = ORDERS.CUSTOMERNUMBER
  INNER JOIN `classic_motors.orderdetails` AS DETAILS
  ON ORDERS.ORDERNUMBER = DETAILS.ORDERNUMBER
  GROUP BY CUSTOMERS.CUSTOMERNAME
),
RNK AS (
  SELECT *,
         RANK() OVER (ORDER BY TBL.AVG_PER_MONTH DESC) AS PER_MONTH_RANKING,
         RANK() OVER (ORDER BY TBL.AVG_PER_ORDER DESC) AS PER_ORDER_RANKING,
         RANK() OVER (ORDER BY TBL.TOTAL DESC) AS TOTAL_RANKING,
  FROM TBL
)

SELECT *,
       PER_MONTH_RANKING + PER_ORDER_RANKING + TOTAL_RANKING AS SUMRANK,
       RANK() OVER (ORDER BY PER_MONTH_RANKING + PER_ORDER_RANKING + TOTAL_RANKING) AS RANKING
FROM RNK
ORDER BY RANKING