SELECT *
FROM `classic_motors.customers` AS CUSTOMERS
INNER JOIN `classic_motors.employees` AS EMPLOYEES
ON CUSTOMERS.SALESREPEMPLOYEENUMBER = EMPLOYEES.EMPLOYEENUMBER
INNER JOIN `classic_motors.offices` AS OFFICES USING(OFFICECODE)
INNER JOIN `classic_motors.orders` AS ORDERS USING(CUSTOMERNUMBER)
INNER JOIN `classic_motors.orderdetails` AS DETAILS USING(ORDERNUMBER)
INNER JOIN `classic_motors.products` AS PRODUCTS USING(PRODUCTCODE)
INNER JOIN `classic_motors.productlines` AS LINES USING(PRODUCTLINE)